# Math on Arrays

## 1. Math on a Single Array 

Being able to do the same calculation on lots of values is at the heart of data sciece. Fortunately, Python and its libraries like NumPy and Pandas make it really easy to do this.

In [2]:
import numpy as np

First, let's make two arrays that contain the high and low temperatures, in Celsius, for four different days. 

In [3]:
lows_C = np.array((2.128, 2.371, 2.874, 3.728))

highs_C = np.array([13.6, 14.387, 14.585, 15.164])

In [4]:
highs_C

array([13.6  , 14.387, 14.585, 15.164])

If we wanted to convert the highs to Farenheit, we could use the following equation: 

$$ T(F) = \frac{9}{5}T(C)+32 $$

What's nice is that we can simply call the array in place of *T(C)*  and it will repeat the same calculation for each value (element) in the array.

In [5]:
(9/5) * highs_C + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

This single line of code is actually doing the following:

<img src = '../images/C_to_F_math.png' width = 600>

Converting Celsius to Farenheit is a pretty common calculation, so we can define a **function** that will allow us to "call" it whenever we need it:

In [14]:
def cel_to_far(celsius):
    return (9/5) * celsius + 32

In [16]:
cel_to_far(highs_C)

array([56.48  , 57.8966, 58.253 , 59.2952])

Usually, we will want to save the new data we have generated into a variable:

In [19]:
highs_F = cel_to_far(highs_C)
highs_F

array([56.48  , 57.8966, 58.253 , 59.2952])

## 2. Math Between Two Arrays

We can also perform operations between two different arrays, as long as they are compatible:

In [21]:
diff = highs_C - lows_C
diff

array([11.472, 12.016, 11.711, 11.436])

<img src = '../images/math_2_arrays.png' width = 600>

# NumPy Functions

For some operations, you will need to code it yourself. However, many calculations are so common that someone else has already written functions for them. Collections of these functions are packaged together into **libraries**.

NumPy has an extensive collection of functions that work on arrays. Hit `tab` after `np.` to see all the functions available:

In [ ]:
np.

In [25]:
np.round(highs_C)

array([14., 14., 15., 15.])

Functions also have arguments, which allow you to customize the function. Press `shift` + `tab` after typing the function to see:

In [ ]:
np.round

If we want to round the temperature to one decimal place instead of a whole number, which is the default, we pass an argument:

In [26]:
np.round(highs_C, decimals = 1)

array([13.6, 14.4, 14.6, 15.2])

Each function is designed to accept only certain data types (single values, strings, floats, etc.) and/or structures (arrays). Here are some NumPy functions that take an array. Try some out for yourself:

#### Array -> Single Value

In [ ]:
np.prod  # multiple all elements together
np.sum  # add all elements together
np.all  # test whether all elements are true values
np.any  # test wether any of the elements are true values
np.count_nonzero  # count the number of nonzero elements

#### Array -> Array

In [ ]:
np.diff # difference between adjacent elements
np.round # round each element to the nearest integer
np.cumprod # for each element, multiply all of the elements so far
np.cumsum # for each element, add all of the elements so far
np.exp # exponentiate each element
np.log # take the natural logarithm of each element
np.sqrt # take the square root of each element
np.sort # sort the elements

#### Array of Strings -> Array

In [ ]:
np.char.lower # lowercase each element
np.char.upper # uppercase each element
np.char.strip # remove spaces at the beginning or end of each element
np.char.isalpha # whether each element is only letters (no numbers or symbols)
np.char.isnumeric # whether each element is only numeric (no letters or symbols)